### ISSUE TITLE
Handlebars draft of dashboard view

### ISSUE THREAD

**Issue by binderb** [binderb/tasqmaster#16]
Acceptance Criteria:
- It's done when there's a `dashboard.handlebars` file in the `view` folder.
- It's done when the file contains an HTML body similar in appearance to `homepage.handlebars`, except that it displays `Dashboard for {{ username }}` at the top.
- It's done when the file is set up to populate with a list of a user's projects.

**Comment by Tvanmeveren** [comment]
i made the dashboard.handlebars in the view folder, copied the homepage.handlebars into it with the dashboard for username up at the top. will show you tomorrow before pushing

**Comment by binderb** [comment]
Cool, sounds like a good start. Concerning the third bullet point, we can work together in class tomorrow to build a route that sends project data to your handlebars template, so that you can populate the list dynamically.

**Comment by binderb** [comment]
![Image](https://user-images.githubusercontent.com/23199743/206595447-72829a33-1429-49ad-aeb5-f51581648663.jpg)
